apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: clouddriver-test
spec:
  template:
    spec:
      containers:
        - image: quay.io/spinnaker/clouddriver:master
          imagePullPolicy: Always
          name: clouddriver
          ports:
            - containerPort: 7002
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/passwords
              name: token-refresh-shared
        - image: quay.io/skuid/ecr-token-refresh:latest
          name: ecr-token-refresh
          imagePullPolicy: Always
          volumeMounts:
           - name: token-refresh-config
             mountPath: /opt/config/ecr-token-refresh
           - name: token-refresh-shared
             mountPath: /opt/passwords
      volumes:
        - name: token-refresh-shared # shared volume
          emptyDir: {}
        - name: token-refresh-config
          configMap:
            name: tokenRefresh.config
